language: generic
os:
  - linux
  - osx

branches:
  only:
    - master
    - latest
    - /^(\d+\.)?(\d+\.)?(\d+)$/

env:
  - GMODPROJ_BUILD_MODE=development

install:
  - sh ./bin/bootstrap.sh

before_script:
  - ./bin/luvi --version || true
  - ./bin/luvit --version || true
  - ./bin/gmodproj version

script:
  - ./bin/gmodproj bin build development

after_success:
  - ./bin/gmodproj bin build production

deploy:
  provider: releases
  api_key:
    secure: Z73zv4gvaCYdsEom3djqw0pCXhrdZysVscmnJ2gHm+u5CrcccuN9NrDsssRtbiwd4v/qgJHusTeJAk+oueOUxnzwC8vxipblrZ9CZ/CNMJHfrBAq4uhbWwFQ8qP5BjRp/92okYGis2Nare+g1ne366eEnCAYJEoVLPju1WHOrUafa2AzpLfzuYav5HZfFP+Am/LA35nWJGjEIOb1WyvyewB/qt4NK35Wfwi1e9chiY1oy5dBEokwsA39luSOeA4NLy4DUOxpWjKhsfJw+wzR0O+rgPgrEDHZn3tXJ7bRbtBkS4IBnbLeyTep46hHz4AgNr76ZC3PMYdIPhenOnwB4K6iCwlehGqTx3u9NW2124/1qCeJkDCDVDN5FTDnLzsmhbsZdnOniLj3uua4ozSnteFbQyJsVxSZh7j7oZat74I1/DI7+FNay+zL5AGCeU/tuVrnbEEDD2zaePtK8EROfp5hlmH5egIp0qI1rwN1C15nne5NBtTyBZbUeqCiAQqYFa/XzCspApRR8DruL0Se+FgcVz0V2NlcRePiLtlRqcJ9v5BQSZx0Dcy1BvWoRUgfDfk8Ho3PLa1vM0PDSijTcJNUAjqj8qi8O89N6fjL/m5BkCu+aBNZtU2r7/IKS3Txu9ldpBaNga5UqyViM1qaw+UICBgMfycJsG+4cpBuDco=
  draft: false
  prerelease: false
  file_glob: true
  file: dist/*
  on:
    repo: novacbn/gmodproj
    tags: true
  skip_cleanup: true